---
#
# Ansible managed
#
repository:
  description: Install the Elastic repository on your system.
  homepage: https://buluma.github.io/
  topics: elasticrepo, ansible, molecule, tox, playbook, hacktoberfest
