---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install elastic product
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - metricbeat
        - elasticsearch-oss
      when:
        - ansible_facts['distribution'] != "Fedora"
