---
- become: true
  gather_facts: false
- name: Verify
  hosts: all
  name: Verify
  tasks:
    - ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - metricbeat
        - elasticsearch-oss
      name: Install elastic product
